name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker pull rabbitmq:3.12.0-management && echo "3exWp5ninMaEcr2T" | docker login --username=kingpanaxi registry.cn-beijing.aliyuncs.com && docker tag rabbitmq:3.12.0-management registry.cn-beijing.aliyuncs.com/firesoulx/rabbitmq:3.12.0-management && docker push registry.cn-beijing.aliyuncs.com/firesoulx/rabbitmq:3.12.0-management
