name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker pull rabbitmq:3.9.22-management
        docker login --username=kingpanaxi -p "3exWp5ninMaEcr2T" registry.cn-beijing.aliyuncs.com
        docker tag rabbitmq:3.9.22-management registry.cn-beijing.aliyuncs.com/firesoulx/rabbitmq:3.9.22-management
        docker push registry.cn-beijing.aliyuncs.com/firesoulx/rabbitmq:3.9.22-management
